name: Build test
on: [push]
jobs:
  Run-Build-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download dependencies
    run: |
      bash download_libraries.sh
    - name: Run make
    run: |
      make -j4
