name: Build test
on: [push]
jobs:
  Run-Build-Test:
    runs-on: ubuntu-latest
    steps:
    - name: Download repo
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt install -y gcc-arm-none-eabi
    - name: Cache STM32F7 support code
      id: cache-stm32f7-support-code
      uses: actions/cache@v3
      with:
        path: STM32CubeF7
        key: x
    - if: ${{ steps.cache-stm32f7-support-code.outputs.cache-hit != 'true' }}
      name: Download STM32F7 support code
      run: |
        bash download_libraries.sh
    - name: Run make
      run: |
        make -j4
